Feature/issue 110
Nefariusek/CodersCamp2021.Project.React-Node pull request #122
Opened 2022-02-19 19:45 UTC by NataliaCichonska

2022-02-19 20:05 UTC, Nefariusek requested changes

2022-02-19 20:05 UTC, Nefariusek commented on backend/src/models/Medication.js
> +  nameOdMedication: { type: String, required: true, minlength: 2, maxlength: 64 },
Typo - should be nameOfMedication

2022-02-20 20:32 UTC, Nefariusek approved these changes

2022-02-21 16:49 UTC, Urszuja commented
Merged

2022-02-21 16:51 UTC, merged