Medication post route
Nefariusek/CodersCamp2021.Project.React-Node pull request #197
Opened 2022-03-20 20:33 UTC by Urszuja

no test provided

2022-03-21 17:19 UTC, Nefariusek requested changes

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  res.status(StatusCodes.OK).json(medication);
remove

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  res.status(StatusCodes.OK).json(medication);
const newMedication = await medication.save();

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  res.status(StatusCodes.OK).json(medication);
const newMedication = await medication.save();

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  const existingMedication = await Medication.findOne({ nameOfMedication: medicationData.nameOfMedication });
check for duplicates for single profile (we have many users with the same medication name)

Use medication.profile as an reference to Profile

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  const existingMedication = await Medication.findOne({ nameOfMedication: medicationData.nameOfMedication });
check for duplicates for single profile (we have many users with the same medication name)

Use medication.profile as an reference to Profile

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  const existingMedication = await Medication.findOne({ nameOfMedication: medicationData.nameOfMedication });
We expect to send a request with id of profile in it

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/userMiddlewares.js
> +}
remove it from this file

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/userMiddlewares.js
> +}
remove it from this file

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  });
you can spread body of request

2022-03-21 17:19 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +  });
you can spread body of request

2022-03-21 17:54 UTC, Urszuja commented on backend/src/middlewares/userMiddlewares.js
> +}
ok

2022-03-21 20:03 UTC, Urszuja commented on backend/src/middlewares/medicationMiddlewares.js
> +  });
ok

2022-03-21 20:03 UTC, Urszuja commented on backend/src/middlewares/medicationMiddlewares.js
> +  });
ok

2022-03-21 20:04 UTC, Urszuja commented on backend/src/middlewares/userMiddlewares.js
> +}
ok

2022-03-22 19:59 UTC, Nefariusek requested changes

2022-03-22 19:59 UTC, Nefariusek commented on backend/src/middlewares/medicationMiddlewares.js
> +      return addedMedication;
We should send a response with added medication instead of returning this document

2022-03-22 20:47 UTC, Nefariusek approved these changes

2022-03-22 20:48 UTC, merged